source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
#platform :ios, '9.1'
use_frameworks!

target 'Baby Sync' do
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON'
    pod 'Google/SignIn'
    pod 'Locksmith', '~> 3.0'
    pod 'AngleGradientLayer', '~> 1.2.3'
end
