source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
#platform :ios, '9.1'
use_frameworks!

target 'Baby Sync' do
    pod 'Alamofire', '~> 3.0'
    pod 'SwiftyJSON', '~> 2.3.1'
    pod 'Google/SignIn'
    pod 'Locksmith'
    pod 'AngleGradientLayer', '~> 1.0'
end
